/*
 * Copyright © 2014 GENBAND. All Rights Reserved.
 *
 * GENBAND CONFIDENTIAL. All information, copyrights, trade secrets
 * and other intellectual property rights, contained herein are the property
 * of GENBAND. This document is strictly confidential and must not be
 * copied, accessed, disclosed or used in any manner, in whole or in part,
 * without GENBAND's express written authorization.
 *
 */



typedef enum restResponseStatus {
    REST_SUCCESSFUL = 0,  // OK
    REST_CREATED = 1,  // CREATED
    REST_PARTIALLY_SUCCESSFUL = 2,
    REST_MALFORMED_USER_NAME = 3,
    REST_AUTHENTICATION_FAILURE = 4,
    REST_INSUFFICIENT_INFO = 5,
    REST_FAILED_TO_CREATE_CLIENT_ID = 6,
    REST_MALFORMED_CLIENT_ID = 7,
    REST_MALFORMED_VERSION = 8,
    REST_DB_EXCEPTION = 9,
    REST_USER_IDENTIFIER_NOT_FOUND = 10,
    REST_MALFORMED_SOCKET_INFO = 11,
    REST_BAD_NOTIFICATION_TYPE =12,
    REST_MISSING_SOCKET_INFO = 13,
    REST_MALFORMED_HTTP_TIMEOUT = 14,
    REST_MALFORMED_REGISTRATION_TTL = 15,
    REST_BAD_DATA_FORMAT = 16,
    REST_NO_PRIMARY_USER = 17,
    REST_BAD_REQUEST_URI = 18,
    REST_TOO_MANY_SESSIONS = 19,
    REST_CLIENT_ID_ALREADY_IN_USE = 20,
    REST_NOTIFICATION_PROXY_NOT_DEFINED = 21,
    REST_NOTIFICATION_PROXY_ERROR = 22,
    REST_NOTIFICATION_RESOURCE_GONE = 23,
    REST_LOCALIZATION_NOT_FOUND = 24,
    REST_MALFORMED_LOCALIZATION = 25,
    REST_INTERNAL_SERVER_ERROR = 26,
    REST_AUTHORIZATION_FAILURE = 27,
    REST_ACCOUNT_DISABLED = 28,
    REST_NOT_AUTHORIZED_DEVICE = 29,
    REST_UNSUPPORTED_VERSION = 30,
    REST_UNSUPPORTED_LOG_TYPE = 31,
    REST_UNSUPPORTED_LOG_DIR = 32,
    REST_INVALID_LOG_OFFSET = 33,
    REST_REUSABLE_CODE = 34,
    REST_SERVICE_NOT_AUTHORIZED =35,
    REST_REUSABLE_CODE2 = 36,   // UNSUPPORTED_PARAMETER_VALUE
    REST_INVALID_PARAMETER_VALUE = 37,
    REST_MALFORMED_MSG = 38,
    REST_DEVICE_SESSION_DOESNT_EXIST = 39,
    REST_NO_SERVICES_SUBSCRIBED = 40,
    REST_REUSABLE_CODE3 = 41,  // INVALID_PARAMETER_VALUE
    REST_RESOURCE_IDENTIFIER_DOES_NOT_EXIST = 42,
    REST_BAD_POLLING_TIMER = 1003,
    REST_JSON_PARSE_ERROR = 1004,
    REST_NO_AVAILABLE_IMRN = 100,
    REST_REMOTE_SERVER_BUSY = 51,
    REST_REQUEST_PENDING = 491,
    REST_REQUEST_PENDING_NOTIFICATION = 49
}SMRestResponseStatus;

